In [2]:
import torch
from torch.nn.functional import softmax
from torch.nn import CrossEntropyLoss

# ignore_index is also -100
from entmax import sparsemax, entmax15, entmax_bisect, entmax15_loss, sparsemax_loss, Entmax15Loss

x = torch.tensor([-2, 0, 0.5])

print(softmax(x, dim=0))
print(sparsemax(x, dim=0))
print(entmax15(x, dim=0))
"""  
tensor([0.0486, 0.3592, 0.5922])
tensor([0.0000, 0.2500, 0.7500])
tensor([0.0000, 0.3260, 0.6740])
"""

tensor([0.0486, 0.3592, 0.5922])
tensor([0.0000, 0.2500, 0.7500])
tensor([0.0000, 0.3260, 0.6740])


'  \ntensor([0.0486, 0.3592, 0.5922])\ntensor([0.0000, 0.2500, 0.7500])\ntensor([0.0000, 0.3260, 0.6740])\n'

In [3]:
print(CrossEntropyLoss().ignore_index)

-100


In [21]:
import torch
from torch.nn.functional import softmax
from torch.nn import CrossEntropyLoss

# ignore_index is also -100
from entmax import sparsemax, entmax15, entmax_bisect, entmax15_loss, sparsemax_loss, Entmax15Loss

loss = CrossEntropyLoss()
input = torch.tensor([[0.1, 0.2, 0.3, 1], [1, 2, 3, 4]])
target = torch.tensor([-100, 1])
output = loss(input, target)
print(output)
input = torch.tensor([[1, 2, 3, 4.0], [1, 2, 3, 4.0]])
target = torch.tensor([1, 1])
output = loss(input, target)
print(output)


tensor(2.4402)
tensor(2.4402)


In [30]:
# ignore_index is also -100
from entmax import sparsemax, entmax15, entmax_bisect, entmax15_loss, sparsemax_loss, Entmax15Loss


loss2 = Entmax15Loss()
input2 = torch.tensor([[0.1, 0.2, 0.3, 1], [1, 2, 3, 4.]])
target2 = torch.tensor([-100, 1])
kept_positions = target2 != -100
print(kept_positions)
target2 = target2[kept_positions]
print(target2)
input2 = input2[kept_positions]
print(input2)
output = loss2(input2, target2)

print(output)

input2 = torch.tensor([[1, 2, 3, 4.]])
target2 = torch.tensor([1])
print(loss2(input2, target2))

tensor([False,  True])
tensor([1])
tensor([[1., 2., 3., 4.]])
tensor(2.0617)
tensor(2.0617)
